### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by satuoqaq** [csnj0/AMA-Det#1]
nice work! When will you release the source code.

**Comment by csnj0** [comment]
This article has remained unnoticed after publication, and I'm almost prepared to quit making the code public. I have a trip planned for this upcoming week, so I'll be sharing the code in the first week of August, and hopefully the work will provide inspiration for you.

**Comment by satuoqaq** [comment]
感谢您的回复，您的工作非常有意义，期待您的开源~


方兆岩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csnj0/AMA-Det"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csnj0/AMA-Det] about code (Issue #1)





 
This article has remained unnoticed after publication, and I'm almost prepared to quit making the code public. I have a trip planned for this upcoming week, so I'll be sharing the code in the first week of August, and hopefully the work will provide inspiration for you.

**Comment by csnj0** [comment]
The initial version has been uploaded, and all the experimental results in the paper can be reproduced. Please cite this paper if it inspires your research work. Thanks.

**Comment by satuoqaq** [comment]
of course! thanks for your code~~~
